language: python
sudo: "required"
services:
  - docker
env:
  matrix:
    - ACTION=bandit
      OS=fedora
      OS_VERSION=29
      PYTHON_VERSION=2
      ENGINE=docker
    - ACTION=bandit
      OS=fedora
      OS_VERSION=29
      PYTHON_VERSION=3
      ENGINE=docker
    - OS=centos
      OS_VERSION=7
      PYTHON_VERSION=2
      ENGINE=docker
    - OS=fedora
      OS_VERSION=29
      PYTHON_VERSION=2
      ENGINE=docker
    - OS=fedora
      OS_VERSION=29
      PYTHON_VERSION=3
      ENGINE=docker
    - OS=fedora
      OS_VERSION=30
      PYTHON_VERSION=3
      ENGINE=docker
script:
 - pip install coveralls
 - ./test.sh
after_success: coveralls
notifications:
  email: false
